print('Enter four scores')
run1=int(input())
run2=int(input())
run3=int(input())
run4=int(input())
Total_run=(run1+run2+run3+run4)
batting_average=(Total_run/4)
print('batting_average is',batting_average)